config/routes.rb
Fire::Application.routes.draw do
  

  devise_for :users, :controllers => { :omniauth_callbacks => 'users' } do
    get '/users/auth/:provider' => 'users#passthru'
  end
  
  resources :users do
    get 'logout', :on => :collection
    get 'importing', :on => :member
  end
  
  get 'u/*id' => 'users#show', :as => "permanent_user"

  root :to => 'users#index'

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable
  devise :rememberable, :omniauthable
  
  embeds_many :positions
  embeds_many :educations
  embeds_many :recommendations
  
  field :num_connections, :type => Integer
  field :num_connections_capped, :type => Boolean
  field :first_name
  field :last_name
  field :name
  field :location
  field :description
  field :public_profile_url
  field :image
  field :industry
  field :summary
  field :num_connections
  field :num_connections_capped
  field :provider
  field :uid
  field :token
  field :secret
  field :positions_attributes
  field :educations_attributes
  field :recommendations_attributes
  field :public
  field :public_id
  field :importing_linkedin_data, :type => Boolean
  
  index :uid
  
  accepts_nested_attributes_for :positions, :educations, :recommendations
  
  attr_accessible :first_name, :last_name, :name, :location, :description, :public_profile_url, :image, :industry,
                  :summary, :num_connections, :num_connections_capped, :provider, :uid, :token, :secret,
                  :positions_attributes, :educations_attributes, :recommendations_attributes, :public,
                  :public_id
  
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :name
  validates_presence_of :public_profile_url
  validates_presence_of :provider
  validates_presence_of :uid
  validates_presence_of :token
  validates_presence_of :secret
  
  before_save :set_public_id
  
  def remember_me
    true
  end
  
  def import_linkedin_data_background
    client = LinkedIn::Client.new(Yetting.linked_in_api_key, Yetting.linked_in_api_secret)
    client.authorize_from_access(self.token, self.secret)
    profile = client.profile(
      :fields => ["industry", "summary", "positions", "educations", "recommendations-received", "num-connections",
                  "num-connections-capped", "picture-url"])

    if profile.positions.all.present?
      profile.positions.all.each do |p|
        p.delete(:id)
        if p.start_date
          p.start_month = p.start_date.month
          p.start_year = p.start_date.year
        end
        if p.end_date
          p.end_month = p.end_date.month
          p.end_year = p.end_date.year
        end
        p.company_id = p.company.id
        p.company_name = p.company.name
        p.company_industry = p.company.industry
      end
      profile.positions_attributes = profile.positions.all
    end
    
    if profile.educations.all.present?
      profile.educations.all.each do |p|
        p.delete(:id)
        if p.start_date
          p.start_month = p.start_date.month
          p.start_year = p.start_date.year
        end
        if p.end_date
          p.end_month = p.end_date.month
          p.end_year = p.end_date.year
        end
      end
      profile.educations_attributes = profile.educations.all
    end
    
    if profile.recommendations_received.all.present?
      profile.recommendations_received.all.each do |p|
        p.delete(:id)
        p.type = p.recommendation_type.code
        p.recommender_id = p.recommender.id
        p.recommender_first_name = p.recommender.first_name
        p.recommender_last_name = p.recommender.last_name
      end
      profile.recommendations_attributes = profile.recommendations_received.all
    end
    
    self.positions.destroy_all
    self.educations.destroy_all
    self.recommendations.destroy_all
    self.attributes = profile
    self.importing_linkedin_data = false
    self.save!
  end
  
  handle_asynchronously :import_linkedin_data_background
  
  def import_linkedin_data
    self.importing_linkedin_data = true
    self.save
    import_linkedin_data_background
  end
  
  def episodes(current_date_number)
    (positions + educations).sort_by! do |e|
      [-e.end_date_number(current_date_number), -e.start_date_number]
    end
  end
  
  def set_public_id
    self.public_id = /.+www\.linkedin\.com\/(.*)/.match(public_profile_url)[1] if public_profile_url.present?
  end
  
end

app/controllers/users_controller.rb
require 'time_helper'

class UsersController < ApplicationController
  include TimeHelper
  
  before_filter :show_current_user, :only => [:index, :linked_in]
  before_filter :ensure_user, :only => [:show, :update, :importing]
  before_filter :ensure_current_user, :only => :update
  
  def index
  end
  
  def show
    now = Time.now
    @current_date_number = date_to_number(now.year, now.month)
    @episodes = @user.episodes(@current_date_number)
    @end_date_number = @episodes.first.end_date_number(@current_date_number) if @episodes.first.present?
  end
  
  def update
    params[:public] = params[:commit].downcase == "public" if params[:commit].present?
    @user.attributes = params
    save = @user.save
    render :json => { :public => @user.public? }.to_json, :status => (save ? :ok : :unprocessable_entity)
  end
  
  def linked_in
    omniauth = request.env["omniauth.auth"]
    user = User.where(:provider => omniauth['provider'], :uid => omniauth['uid']).first
    if user
      user.update_attributes(omniauth['credentials'])
      user.import_linkedin_data
      sign_in_and_redirect(user)
      return
    else
      user = User.new({ :provider => omniauth['provider'], :uid => omniauth['uid'], :public => false }.
        merge!(omniauth['credentials']).merge!(omniauth['user_info']))
      if user.save
        user.import_linkedin_data
        sign_in_and_redirect(user)
        return
      end
    end
    # New user data not valid, try again
    flash[:alert] = t('users.linkedin_failed')
    redirect_to users_path
  end
  
  def passthru
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end
  
  def failure
    flash[:alert] = t('users.linkedin_failed')
    redirect_to users_path
  end
  
  def logout
    sign_out_and_redirect(:user)
  end
  
  def destroy
    current_user.destroy if current_user
    sign_out_and_redirect(:user)
  end
  
  def importing
    render :json => { :importing => @user.importing_linkedin_data? }
  end
  
  private
  
  def show_current_user
    redirect_to permanent_user_path(current_user.public_id) if current_user
  end
  
  def ensure_user
    @user = User.find(params[:id]) if params[:id] !~ /\//
    @user = User.where(:public_id => params[:id]).first unless @user
    @user = User.where(:public_id => URI.escape(params[:id])).first unless @user
    redirect_to users_path if @user.blank? || (!@user.public? && @user != current_user)
  end
  
  def ensure_current_user
    redirect_to users_path unless @user == current_user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_card.html.haml
- html_attributes = card.start_date_number > 0 ? { :'data-start' => @end_date_number - card.start_date_number + 1,
  :'data-end' => @end_date_number - card.end_date_number(@current_date_number) } : {}
- case card
  - when Position
    = render :partial => "users/position", :object => card, :locals => { :html_attributes => html_attributes }
  - when Education
    = render :partial => "users/education", :object => card, :locals => { :html_attributes => html_attributes }

app/views/users/_education.html.haml
.education.card{ html_attributes }
  .header
    .title
      = education.school_name
    .degree
      - if education.degree.present?
        = "#{education.degree}#{"," if education.field_of_study.present?}"
      = education.field_of_study if education.field_of_study.present?
  .body
    - if education.start_date_number > 0
      .duration
        = "#{Date::MONTHNAMES[education.start_month.to_i]} #{education.start_year}"
        &mdash;
        = education.current? ? "Present" : "#{Date::MONTHNAMES[education.end_month.to_i]} #{education.end_year}"

app/views/users/_position.html.haml
.position.card{ html_attributes }
  .header
    .title
      = position.title
    .company
      = position.company_name
  .body
    - if position.start_date_number > 0
      .duration
        = "#{Date::MONTHNAMES[position.start_month.to_i]} #{position.start_year}"
        &mdash;
        = position.current? ? "Present" : "#{Date::MONTHNAMES[position.end_month.to_i]} #{position.end_year}"
    - if position.summary.present?
      .summary
        = simple_format(position.summary)

app/views/users/index.html.haml
%h1.title

%h2.tag-line
  Visualize your LinkedIn profile in a timeline.

%a.button{ :href => "/users/auth/linked_in" }
  = image_tag "linkedin_logo.png"
  %p
    Connect to
    
%p.disclaimer
  Disclaimer: Your data is private by default. You can delete your data at any time.

app/views/users/show.html.haml
- content_for :head do
  %meta{ :property => "og:title",
         :content => "#{@user.first_name.possessive + " " if @user.first_name.present?}Professional Timeline" }
  %meta{ :property => "og:type", :content => "website" }
  %meta{ :property => "og:url", :content => request.url }
  %meta{ :property => "og:image",
         :content => (@user.image.present? ? @user.image : asset_path("share_placeholder.png")) }
  %meta{ :property => "og:site_name", :content => "LN Timeline" }
  %meta{ :property => "og:description", :content => t("users.og_description") }
  %meta{ :property => "fb:admins", :content => "215918" }

.nav-container
  .nav
    - if @user == current_user
      = form_for(@user, :html => { :class => "privacy #{@user.public? ? "public" : "private"}" },
        :remote => true) do |f|
        = f.submit "Private", :class => "private-button button", :disable_with => "Saving..."
        = f.submit "Public", :class => "public-button button", :disable_with => "Saving..."
    .social-networks{ :class => "#{@user.public? ? "public" : "private"}" }
      %ul.private-share
        %li.facebook{ :title => "Profile is not public" }
        %li.twitter{ :title => "Profile is not public" }
        %li.linkedin{ :title => "Profile is not public" }
        %li.google{ :title => "Profile is not public" }
      %ul.public-share
        %li
          %fb:like{ :href => request.url, :send => false, :layout => "button_count", :show_faces => false,
            :font => "lucida grande" }
        %li
          %a{ :href => "https://twitter.com/share", :class => "twitter-share-button",
              "data-text" => "LinkedIn profile in a timeline" } Tweet
        %li
          %script{ :type => "IN/Share", "data-url" => request.url, "data-counter" => "right" }
        %li
          %g:plusone{ :size => "medium" }
    - if @user == current_user
      %p
        = link_to t("users.sign_out"), logout_users_path
      %p
        = link_to t("users.delete_profile"), user_path(current_user), :method => :delete
    - else
      %p
        = link_to t("users.my_profile"), users_path
    - if @user.importing_linkedin_data?
      %p.importing{ "data-check-url" => importing_user_path(@user) }
        = t("users.importing_profile")
        
    

.card.profile-header
  .picture
    = image_tag(@user.image.blank? ? asset_path("profile.png") : @user.image)
  
  - if @user.location.present? || @user.industry.present?
    .sub-header
      - if @user.industry.present?
        %p.industry
          = @user.industry
      - if @user.location.present? && @user.industry.present?
        .vertical-divider
      - if @user.location.present?
        %p.location
          = @user.location
    
  %h1.name
    = @user.name
  - if @user.description.present?
    %p.description
      = @user.description
  .info
    .clip.connections
      = "#{@user.num_connections}#{@user.num_connections_capped? ? "+" : ""}"
    - if @user.location.present?
      .clip
        %a{ :href => "http://maps.google.com?q=#{URI.escape(@user.location)}", :target => "_blank"}
          %img{ :src => "http://maps.googleapis.com/maps/api/staticmap?markers=#{URI.escape("color:green|size:small|"+@user.location)}&size=110x70&sensor=false" }
    - if @user.summary.present?
      = @user.summary

.timeline-container{ :'data-end-date-number' => @end_date_number }
  = render :partial => "users/card", :collection => @episodes
  .timeline
    .extent
    
#fb-root